### ISSUE TITLE
Membuat Sistem di Tampilan History Check -> Tampilan 2 - Detail

### ISSUE THREAD

**Issue by NRayaa** [NRayaa/BackEnd-Liquid8#10]
Naahhhh harusnya disini sih jelasinnya,

Tampilan ini juga bisa diakses, waktu di halaman check product trus klik "DONE CHECK" 

Jadi fungsi utama dari detail ini untuk report dari check document
lalu untuk di print, untuk laporan ke pihak supplier

nah ini nih yang harus ada di tampilan : 

 - CODEDOC : misal:DOCUMEN001/2023
 - Base File : misal: LAZADA001 (file yg diupload)
 - Jumlah kolom tabel : misal:1000 (jumlah kolom dari file)

Trus ada tabel dibawah bentuknya kayak gini persis, trus ada chart pie nya juga, aku kasih foto aja yaa....
![image](https://github.com/NRayaa/BackEnd-Liquid8/assets/116838581/560cf65c-e1eb-4080-aa07-4d9f0af01fae)

NOTE -> Chart Pie nya itu kalo ada 4 warna (3, 4, 5, 6) NAH TOTAL NYA ITU ADA DI (TOTAL DATA)

Nah jadi isian nya itu ini, gweh jelasin : 
1. Total Data => Jumlah kolom nya
2. Total Data In => Jumlah kolom yang sudah dicheck -> (kolom = barang)
3. Total Data Lolos => Jumlah kolom dengan quality check nya -> lolos
4. Total Data Damged => Jumlah kolom dengan quality check nya -> Damaged
5. Total Data Abnormal => Jumlah kolom dengan quality check nya -> Abnormal
6. Total Data Discrepancy => Pengurangan Total Data - Total Data In

btw aku kurang tau kalo data perhitungan gini, harus di masukin database dulu apa ga?
Kalo emang butuh dimasukin ke database, buatin dulu gpp. trus design yang baru masukin ke comment di bawah yaaa.....

**Comment by laluisari** [comment]
![Image](https://github.com/NRayaa/BackEnd-Liquid8/assets/82717953/64aa47f1-55b1-4c7f-a90a-9b5f61b8b4f0)
