### ISSUE TITLE
Membuat Design Database

### ISSUE THREAD

**Issue by NRayaa** [NRayaa/BackEnd-Liquid8#2]
Selamat Datang Cuy, kita mulai dengan design database yak.....
Kali ini gweh ga akan buat yang sulit kayak kemarin T-T sory co

Nah ada beberapa tabel untuk konfigurasi awal, cuma ini agak panjang sih

DIBACA SAMPE AKHIR YA COY AWKAWKAKW : 

======================================================================================
1. Tabel Document
- id
- code_document -> (unique)
- base_document -> diambil dari nama file waktu upload
- total_column_document -> diambil dari jumlah kolom di dalam file yg di upload
- total_column_in_document -> diambil dari jumlah barang yang sudah dicek, dan ada
- date_document -> diambil dari waktu dokumen di upload
- status_document -> ada 3 jenis status (pending, in progress, done) nanti aku kasih penjelasan note di bawah ini

NOTE UNTUK TABEL DOCUMENT : 
- pending tuh ketika di dalam halaman list trus detail nanti ada button (continue) / ketika setelah upload file nanti juga ada button (continue) nya blom di pencet
- In Progress tuh ketika button (continue) nya udah di klick, tapi button yang di dalam halaman check product (DONE CHECK) nya blom diklick
- Done tuh ketika button (DONE CHECK) nya sudah di klick -> dihalaman check product
- code_document -> dipakai untuk pengechekan, jadi nanti code_document itu di detail nya ada continue nya, nah nanti data yang code documentnya sama, yang akan dicheck dan datanya cuma yang sesuai dengan code_documentnya.

======================================================================================
2. Tabel Product Old
- id
- code_document
- old_barcode_product -> no resi nanti yang sesuai dengan data di dalam file yang di upload
- old_name_product -> nama barang nanti yang sesuai dengan data di dalam file yang di upload
- old_quantity_product -> quantity nanti yang sesuai dengan data di dalam file yang di upload
- old_price_product -> harga nanti yang sesuai dengan data di dalam file yang di upload

NOTE UNTUK TABEL PRODUCT OLD : 
- jadi product old nya ini akan ke upload otomatis ketika setelah memilih header yang sesuai
- dan diselipkan code document yang sesuai juga
- INGET, ini ga ada relasi. code document nya dimasukin biasa aja, bukan by id reference
- KENAPA? KALO GITU KAN KALO PARENT NYA KEHAPUS, CHILD NYA MASIH ADA TO??????
- iya emang gitu, karena data kayak gini gaboleh kehapus gitu aja. PENCATATAN ITU BAGIAN PENTING YA GEYS, JADI GA BOLEH TERHUBUNG SAMA APA APA.

======================================================================================
3. Tabel New Product
- id
- code_document
- old_barcode_product
- new_barcode_product -> ini auto generate ya, trus munculnya ketika button lolos di halaman check product
- new_name_product -> diambil dari old_name_product, tapi di pindah aja ke tabel baru
- new_quantity_product -> diambil juga dari old_quantity_prodcut, tapi di pindah aja ke tabel baru
- new_price_product -> diambil dari nanti perhitungan yang ada, ntar aku jelasin di note bawah okeyy....
- new_date_in_product -> sebenernya ini diambil dari date_document sih, tapi ntar terserah kalian enaknya gimana(tapi bukan by id reference ya)
- new_status_product -> nah ini ada 5 jenis status (display, expired, promo, bundle, palet), ntar gweh jelasin dibawah
- new_category_product -> ini juga ada tabelny sendiri nanti, cuma ga usah di relasiin, ntar gweh aturin caranya
- new_tag_product -> ini ada 2 isian biasanya, cuma tergantung sama tabel tag ntar (tag warna), sama ga dibuat relasi lho ya >:D

NOTE UNTUK TABEL PRODUCT NEW
- code_document tetep harus ada ya, buat reporting nya nanti
- old_barcode_product sebenernya buat jaga" kalo dibutuhin aja si
- NAHHH yg new price product -> itu nanti dibagi ada 3, cuma itu nanti task selanjutnya aja si, di database ini yang penting bisa nampung itu aja MWEHEWHEWHE >:D
- STATUS NIH, ada 5 nanti ini gunanya buat product ini di tampilin dimana aja, sama dihilangin di halaman mana aja, gituuuu
- trus new category sama new tag itu, emg ga aku relasiin, soalnya buat pencatatan geysss.

======================================================================================
4. Tabel Promo
- id
- new_product_id -> relasi dengan tabel new product
- name_promo -> ini nanti diinputin biasa, pake form
- discount_promo -> ini ntar jadi perhitungan
- price_promo -> ini ntar jadi harga setelah perhitungan

NOTE UNTUK TABEL PROMO 
- awkoakwoak dikit juga tabel nieee
- TADI GA USAH PAKE RELASI, TAPI SEKARANG MALAH PAKE YG NEW_PRODUCT_ID, GIMANA SIIII??????
- iya geysss, karena nanti kalo product nya ilang, masa promo nya masih, kan lucu bejir >:D
- nanti perhitungannya dari discount*new_price_product -> hasilnya masuk ke kolom price_promo

======================================================================================
5. Tabel Bundle
- id
- name_bundle -> ini inputan biasa
- total_price_bundle -> ini jumlah dari barang yang masuk id bundle nya
- total_product_bundle -> ini juga jumlah dari ada berapa barang yang masuk id bundle nya
- date_create_bundle

NOTE UNTUK TABEL BUNDLE -> DIKIT BANGET BEJIR
- nah ini sebenernya buat nampung id list barang yang mau dibundle
- nantinya id nya jadi patokan dan di relasiin sama tabel list produk

======================================================================================
6. Tabel Palet
- id
- name_palet
- category_palet
- total_price_palet
- total_product_palet
- date_create_palet

NOTE UNTUK TABEL PALET, INI JUGA DIKIT BANGET CO
- sebenernya ini sama kayak bundle, nanti kalian kalo mau gabungin juga gapapa, cuma kasih note yaaa......
- Trus ini category palet -> diambil dari tabel kategori, cumaaaa ga relasi INGET YA, ini dimasukin dari inputan kok, jadi ga pake relasi

======================================================================================
7. Tabel List Product BP  => FYI : BP tu Bundle & Palet
- id
- new_product_id -> ini relasi ya guys dengan tabel new product
- bundle_id -> ini ntar keiisi kalo lagi buat bundle
- palet_id -> ini ntar keiisi kalo lagi buat palet

NOTE BUAT TABEL LIST PRODUCT BP, AWKOAKWOAK TAMBAH DIKIT
- ini relasi diperlukan biar ntar bisa ngikut parentnya ntar

======================================================================================
8. Tabel Category
- id
- name_category 
- discount_category
- max_price_category

NOTE BUAT TABEL CATEGORY
- gada sih, buat dulu aja yak :p 

======================================================================================
9. Table Color Tag
- id
- hexa_code_color
- name_color
- min_price_color
- max_price_color
- fixed_price_color

NOTE UNTUK TABEL COLOR TAG
- nah ini ada note buat klean
- jadi fixed price itu akan kepake, kalo data dari old_price_product diantara min dan max price color

======================================================================================

DAH DULU GUYS, JADI INI MASIH PATCH 1 YAH, NANTI KITA BUAT LAGI UNTUK PATCH SELANJUTNYA
MUNGKIN UNTUK PENJUALAN, MIGRASI, BARANG RUSAK(OUT), DLL
SEMANGAT CUY >:D

oiya nih ada gambaran dikit : 
![Design Database Patch 1](https://github.com/NRayaa/BackEnd-Liquid8/assets/116838581/e53bc966-53fd-4ce7-9641-4f8f6a21e5e2)

**Comment by laluisari** [comment]
desain database sudah jadi di drawsql 


![Image](https://github.com/NRayaa/BackEnd-Liquid8/assets/82717953/78e11339-48f5-4505-93e5-82ee1765142b)

**Comment by NRayaa** [comment]
Approved, Nicee cuy
