### ISSUE TITLE
Membuat Sistem di Tampilan List Data -> Tampilan 1

### ISSUE THREAD

**Issue by NRayaa** [NRayaa/BackEnd-Liquid8#6]
Nahhhhh sekarang udah pindah menu yaitu List Data

Disini nanti bakal nampilin data" yang ada di tabel DOCUMENT

jadi nanti tu bentuknya  tabel, ini nih headernya :
1. | NO | CODE DOCUMENT | DATE IN | TOTAL COLUMN | OPSI |

nah itu aja sih, nanti isinya sesuai di dalam tabel, okeee?
oiya :  
1. TOTAL COLUMN dapet dari jumlah nya semua kolom file upload yang sesuai dengan code document

Gitu aja si akawkakwka, oke deh lanjut

**Comment by laluisari** [comment]
![Image](https://github.com/NRayaa/BackEnd-Liquid8/assets/82717953/3bec20ac-6af8-4794-ac4b-4c97c18b51af)
