### ISSUE TITLE
Membuat Sistem di Tampilan List Data -> Tampilan 2 - Detail

### ISSUE THREAD

**Issue by NRayaa** [NRayaa/BackEnd-Liquid8#7]
Ini nanti buat untuk detail nya, di dalem tampilan ini bakal nampilin ini aja : 
1. CODEDOC : misal:DOCUMEN001/2023 -> dari tabel document -> kolom code_Document
2. Base File : misal: LAZADA001 (file yg diupload) -> dari tabel document -> kolom base_document
3. Jumlah kolom tabel : misal:1000 (jumlah kolom dari file) -> dari tabel document -> kolom total_column_document

Trus nanti bakal munculin tabel list, dengan headernya ini : 
1. No
2. No Resi
3. Nama Barang
4. Quantity
5. Harga

1. Ada button untuk CONTINUE

nah di atas tabel ntar ada tombol continue yang fungsinya untuk melempar semua code_Document yang dipilih, biar semua Porduct old yg code_Documentnya sama bisa di cek satu persatu nantinya

**Comment by laluisari** [comment]
detail dari document 


![Image](https://github.com/NRayaa/BackEnd-Liquid8/assets/82717953/0261f42c-687f-4f14-8e94-433dcc6d7cde)

dan nanti akan munculin data sesuai nomor code_document nya untuk di check 


![Image](https://github.com/NRayaa/BackEnd-Liquid8/assets/82717953/0dd094a5-c143-4a0f-9e97-1cbb8f188a45)
