### ISSUE TITLE
Membuat Sistem di Tampilan History Check -> Tampilan 1

### ISSUE THREAD

**Issue by NRayaa** [NRayaa/BackEnd-Liquid8#9]
Bentuk nya masih list tabel biasa sih,

NIh ya gweh kasih tau : 
1. jadi data ini diambil dari tabel DOCUMENT -> tapi dengan status done aja
2. Trus kalian bisa pake find all()
3. cuma ntar ada tombol detail -> yang harus nglempar parameter sehingga bisa dilihat detailnya
4. nah ntar di dalam detail itu ada data dokumennya kayak gini 
 - CODEDOC : misal:DOCUMEN001/2023
 - Base File : misal: LAZADA001 (file yg diupload)
 - Jumlah kolom tabel : misal:1000 (jumlah kolom dari file)

5. Trus ada tabel dibawah bentuknya kayak gini persis, aku kasih foto aja yaa....
![image](https://github.com/NRayaa/BackEnd-Liquid8/assets/116838581/48c5def4-8bd5-45a0-a5a0-f2180eac0707)

Nah jadi isian nya itu ini, gweh jelasin : 
1. Total Data => Jumlah kolom nya
2. Total Data In => Jumlah kolom yang sudah dicheck -> (kolom = barang)
3. Total Data Lolos => Jumlah kolom dengan quality check nya -> lolos
4. Total Data Damged => Jumlah kolom dengan quality check nya -> Damaged
5. Total Data Abnormal => Jumlah kolom dengan quality check nya -> Abnormal
6. Total Data Discrepancy => Pengurangan Total Data - Total Data In

Njir malah gwe jelasin disini, yaudah sampe situ aja ya. habis ini lanjut

**Comment by laluisari** [comment]
history done 


![Image](https://github.com/NRayaa/BackEnd-Liquid8/assets/82717953/4c4442ee-f807-403d-b6a1-1fbb1bd18b6f)


tidak bisa mengirimkan data document 2x 



![Image](https://github.com/NRayaa/BackEnd-Liquid8/assets/82717953/3ae5a6b1-147a-4027-badc-cc3b87c83124)
